// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5yjEv4rqS43EbE_39_xzvY-jAMo4l5cc',
    appId: '1:817289222181:web:a3777752a3a372153f47cc',
    messagingSenderId: '817289222181',
    projectId: 'peshooscanner',
    authDomain: 'peshooscanner.firebaseapp.com',
    storageBucket: 'peshooscanner.firebasestorage.app',
    measurementId: 'G-SXK2LCC1DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BAf0bOKGF7dysohgkK7XeaaYkku5TtM',
    appId: '1:817289222181:android:9832f7e6e269c9d83f47cc',
    messagingSenderId: '817289222181',
    projectId: 'peshooscanner',
    storageBucket: 'peshooscanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbd9aRA7zCWBXNtFri29NDtVXBNCFhqQY',
    appId: '1:817289222181:ios:1d2abf804604b3a23f47cc',
    messagingSenderId: '817289222181',
    projectId: 'peshooscanner',
    storageBucket: 'peshooscanner.firebasestorage.app',
    iosBundleId: 'com.peshoo.scanner.peshooScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbd9aRA7zCWBXNtFri29NDtVXBNCFhqQY',
    appId: '1:817289222181:ios:1d2abf804604b3a23f47cc',
    messagingSenderId: '817289222181',
    projectId: 'peshooscanner',
    storageBucket: 'peshooscanner.firebasestorage.app',
    iosBundleId: 'com.peshoo.scanner.peshooScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5yjEv4rqS43EbE_39_xzvY-jAMo4l5cc',
    appId: '1:817289222181:web:93b0652fae208f213f47cc',
    messagingSenderId: '817289222181',
    projectId: 'peshooscanner',
    authDomain: 'peshooscanner.firebaseapp.com',
    storageBucket: 'peshooscanner.firebasestorage.app',
    measurementId: 'G-YG3J0EQFYN',
  );
}
